default: &default_params
    # for Preparing data
    batch_size: 15
    num_batches: 1500
    truncate_len: 1000
    step_size: 500
    # for HM-LSTM nets
    learning_rate: 1e-4
    num_layers: 3
    output_size: 27
    input_size: 27
    embed_size: 2048
    out_hidden_size: 1024
    hidden_state_sizes: 1024
    epochs: 2
    quick_dev: false
    valid_after_step: 100

large_batch:
    <<: *default_params
    batch_size: 10
    num_batches: 2500
    learning_rate: 2e-4
    epochs: 1

deep_nets:
    # fail
    <<: *default_params
    num_layers: 4
    batch_size: 10

small_nets:
    <<: *default_params
    embed_size: 1024
    out_hidden_size: 512
    hidden_state_sizes: 512

small_trun_len:
    <<: *default_params
    embed_size: 1024
    truncate_len: 500
    step_size: 250

less_layer:
    <<: *default_params
    num_layers: 2

quick_net:
    <<: *default_params
    batch_size: 5